export const FIND_DOCTOR_REQUEST = "FIND_DOCTOR_REQUEST";
export const FIND_DOCTOR_SUCCESS = "FIND_DOCTOR_SUCCESS";
export const FIND_DOCTOR_FAIL = "FIND_DOCTOR_FAIL";

export const GET_PATIENT_APPOINTMENTS_REQUEST =
  "GET_PATIENT_APPOINTMENTS_REQUEST";
export const GET_PATIENT_APPOINTMENTS_SUCCESS =
  "GET_PATIENT_APPOINTMENTS_SUCCESS";
export const GET_PATIENT_APPOINTMENTS_FAIL = "GET_PATIENT_APPOINTMENTS_FAIL";
