export const POST_BLOG_REQUEST = "POST_BLOG_REQUEST";
export const POST_BLOG_SUCCESS = "POST_BLOG_SUCCESS";
export const POST_BLOG_FAIL = "POST_BLOG_FAIL";

export const GET_BLOGS_REQUEST = "GET_BLOGS_REQUEST";
export const GET_BLOGS_SUCCESS = "GET_BLOGS_SUCCESS";
export const GET_BLOGS_FAIL = "GET_BLOGS_FAIL";

export const GET_SINGLE_BLOG_REQUEST = "GET_SINGLE_BLOG_REQUEST";
export const GET_SINGLE_BLOG_SUCCESS = "GET_SINGLE_BLOG_SUCCESS";
export const GET_SINGLE_BLOG_FAIL = "GET_SINGLE_BLOG_FAIL";

export const GET_PERSONAL_BLOGS_REQUEST = "GET_PERSONAL_BLOGS_REQUEST";
export const GET_PERSONAL_BLOGS_SUCCESS = "GET_PERSONAL_BLOGS_SUCCESS";
export const GET_PERSONAL_BLOGS_FAIL = "GET_PERSONAL_BLOGS_FAIL";

export const POST_BLOG_COMMENT_REQUEST = "POST_BLOG_COMMENT_REQUEST";
export const POST_BLOG_COMMENT_SUCCESS = "POST_BLOG_COMMENT_SUCCESS";
export const POST_BLOG_COMMENT_FAIL = "POST_BLOG_COMMENT_FAIL";

export const GET_BLOG_COMMENTS_REQUEST = "GET_BLOG_COMMENTS_REQUEST";
export const GET_BLOG_COMMENTS_SUCCESS = "GET_BLOG_COMMENTS_SUCCESS";
export const GET_BLOG_COMMENTS_FAIL = "GET_BLOG_COMMENTS_FAIL";
