export const POST_QUESTION_REQUEST = "POST_QUESTION_REQUEST";
export const POST_QUESTION_SUCCESS = "POST_QUESTION_SUCCESS";
export const POST_QUESTION_FAIL = "POST_QUESTION_FAIL";

export const GET_QUESTIONS_REQUEST = "GET_QUESTIONS_REQUEST";
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";
export const GET_QUESTIONS_FAIL = "GET_QUESTIONS_FAIL";

export const GET_SINGLE_QUESTION_REQUEST = "GET_SINGLE_QUESTION_REQUEST";
export const GET_SINGLE_QUESTION_SUCCESS = "GET_SINGLE_QUESTION_SUCCESS";
export const GET_SINGLE_QUESTION_FAIL = "GET_SINGLE_QUESTION_FAIL";

export const GET_PERSONAL_QUESTIONS_REQUEST = "GET_PERSONAL_QUESTIONS_REQUEST";
export const GET_PERSONAL_QUESTIONS_SUCCESS = "GET_PERSONAL_QUESTIONS_SUCCESS";
export const GET_PERSONAL_QUESTIONS_FAIL = "GET_PERSONAL_QUESTIONS_FAIL";

export const POST_ANSWER_REQUEST = "POST_ANSWER_REQUEST";
export const POST_ANSWER_SUCCESS = "POST_ANSWER_SUCCESS";
export const POST_ANSWER_FAIL = "POST_ANSWER_FAIL";
