export const SOCKET_CONNECTION_REQUEST = "SOCKET_CONNECTION_REQUEST";
export const SOCKET_CONNECTION_SUCCESS = "SOCKET_CONNECTION_SUCCESS";
export const SOCKET_CONNECTION_FAIL = "SOCKET_CONNECTION_FAIL";
export const SOCKET_DISCONNECT = "SOCKET_DISCONNECT";
